CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    type TEXT NOT NULL DEFAULT 'checking',
    currency TEXT NOT NULL DEFAULT 'USD',
    opening_balance NUMERIC NOT NULL DEFAULT 0,
    active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
    created_at TEXT NOT NULL,
    opening_balance_cents BIGINT NOT NULL DEFAULT 0,
    CHECK(opening_balance = opening_balance_cents / 100.0)
);
CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TEXT NOT NULL CHECK(date = to_char(date::date, 'YYYY-MM-DD')),
    type TEXT NOT NULL CHECK(type IN ('income','expense')),
    category TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    description TEXT,
    account_id BIGINT REFERENCES accounts(id) ON DELETE SET NULL,
    amount_cents BIGINT NOT NULL CHECK(amount_cents > 0),
    deleted_at TEXT,
    CHECK(amount = amount_cents / 100.0)
);
CREATE TABLE recurring_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL CHECK(type IN ('income','expense')),
    category TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    description TEXT,
    frequency TEXT NOT NULL CHECK(frequency IN ('daily','weekly','monthly','yearly')),
    next_date TEXT NOT NULL CHECK(next_date = to_char(next_date::date, 'YYYY-MM-DD')),
    active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
    account_id BIGINT REFERENCES accounts(id) ON DELETE SET NULL,
    amount_cents BIGINT NOT NULL CHECK(amount_cents > 0),
    CHECK(amount = amount_cents / 100.0)
);
CREATE TABLE budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT UNIQUE NOT NULL,
    monthly_limit NUMERIC NOT NULL,
    month_year TEXT NOT NULL,
    monthly_limit_cents BIGINT NOT NULL CHECK(monthly_limit_cents > 0),
    CHECK(monthly_limit = monthly_limit_cents / 100.0)
);
CREATE TABLE transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TEXT NOT NULL CHECK(date = to_char(date::date, 'YYYY-MM-DD')),
    from_account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE RESTRICT,
    to_account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE RESTRICT,
    amount NUMERIC NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    amount_cents BIGINT NOT NULL CHECK(amount_cents > 0),
    CHECK(from_account_id <> to_account_id),
    CHECK(amount = amount_cents / 100.0)
);
CREATE TABLE settings (key TEXT PRIMARY KEY, value TEXT);
CREATE TABLE schema_migrations (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL);
CREATE TABLE recurring_occurrences (
    recurring_id BIGINT NOT NULL REFERENCES recurring_transactions(id) ON DELETE RESTRICT,
    due_date TEXT NOT NULL,
    PRIMARY KEY(recurring_id, due_date)
);
CREATE TABLE transaction_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT NOT NULL REFERENCES transactions(id) ON DELETE RESTRICT,
    action TEXT NOT NULL CHECK(action IN ('created','updated','deleted','restored')),
    occurred_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    actor TEXT NOT NULL DEFAULT 'local',
    before_state TEXT CHECK(before_state IS NULL OR jsonb_typeof(before_state::jsonb)='object'),
    after_state TEXT NOT NULL CHECK(jsonb_typeof(after_state::jsonb)='object')
);
CREATE TABLE reconciliations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE RESTRICT,
    closing_date TEXT NOT NULL CHECK(closing_date = to_char(closing_date::date, 'YYYY-MM-DD')),
    opening_balance_cents BIGINT NOT NULL,
    closing_balance_cents BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','completed')),
    created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    completed_at TEXT,
    UNIQUE(id, account_id),
    UNIQUE(account_id, closing_date)
);
CREATE UNIQUE INDEX idx_reconciliation_draft ON reconciliations(account_id) WHERE status='draft';
CREATE TABLE reconciliation_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reconciliation_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    transaction_id BIGINT REFERENCES transactions(id) ON DELETE RESTRICT,
    transfer_id BIGINT REFERENCES transfers(id) ON DELETE RESTRICT,
    CHECK((transaction_id IS NULL) <> (transfer_id IS NULL)),
    FOREIGN KEY(reconciliation_id, account_id) REFERENCES reconciliations(id, account_id),
    UNIQUE(account_id, transaction_id),
    UNIQUE(account_id, transfer_id)
);
CREATE INDEX idx_transactions_account_date ON transactions(account_id,date);
CREATE INDEX idx_transactions_deleted ON transactions(deleted_at,date);
CREATE INDEX idx_transfers_date ON transfers(date);
CREATE INDEX idx_transfers_from_account ON transfers(from_account_id);
CREATE INDEX idx_transfers_to_account ON transfers(to_account_id);
CREATE INDEX idx_recurring_account ON recurring_transactions(account_id);
CREATE INDEX idx_transaction_audit_history ON transaction_audit(transaction_id,id);
CREATE INDEX idx_reconciliation_entries ON reconciliation_entries(reconciliation_id);

CREATE VIEW reconciliation_ledger AS
SELECT account_id, id AS entry_id, 'transaction'::text AS kind, date,
       COALESCE(description,'') AS description, category AS label,
       CASE WHEN type='income' THEN amount_cents ELSE -amount_cents END AS amount_cents
FROM transactions WHERE deleted_at IS NULL
UNION ALL
SELECT t.from_account_id, t.id, 'transfer', t.date, t.description,
       'Transfer to ' || a.name, -t.amount_cents
FROM transfers t JOIN accounts a ON a.id=t.to_account_id
UNION ALL
SELECT t.to_account_id, t.id, 'transfer', t.date, t.description,
       'Transfer from ' || a.name, t.amount_cents
FROM transfers t JOIN accounts a ON a.id=t.from_account_id;
